name: proxy-services

services:
  mtg:
    image: nineseconds/mtg:2
    container_name: mtg
    restart: unless-stopped
    ports:
      - ${MTG_PORT:-8443}:443
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - /usr/local/share/proxy_services/mtg/config.toml:/config/config.toml:ro
