name: proxy-services

services:
  tg-proxy:
    container_name: tg-proxy
    image: telegrammessenger/proxy:latest
    restart: unless-stopped
    ports:
      - ${TG_PROXY_PORT:-443}:443
    environment:
      - TZ=${TZ:-UTC}
    env_file:
      - /usr/local/share/proxy_services/tg_proxy/.env
    volumes:
      - tg-proxy-data:/data

volumes:
  tg-proxy-data:
