user nginx;
worker_processes auto;

pid /run/nginx.pid;
error_log /dev/stderr {{ if eq .log.level "warning" -}} warn
                      {{- else -}} {{.log.level }}
                      {{- end }};

events {
  worker_connections  4096;
}

http {
{{- if eq .log.level "debug" "info" }}
  log_format http_log '[$time_local] $remote_addr > $scheme://$host "$request" ($http_x_forwarded_for)';
  access_log /dev/stdout http_log;
{{- else }}
  access_log off;
{{- end }}

  http2 on;

  server {
    listen 80;
    listen [::]:80;

    # Pass acme challenges to acme.sh container
    location /.well-known/acme-challenge/ {
      proxy_pass http://172.22.0.3;
    }

    location / {
      return 308 https://$host$request_uri;
    }
  }

  server {
    listen 8443 ssl;
    listen [::]:8443 ssl;

    ssl_certificate /etc/nginx/certs/$ssl_server_name.crt;
    ssl_certificate_key /etc/nginx/certs/$ssl_server_name.key;
    ssl_certificate_cache max=1000 inactive=1h valid=1h;

    # If secret path is set, route traffic to xray's xhttp inbound
    location {{ .local.xray.xhttp.path }} {
      proxy_pass http://172.22.0.11:2443;
      proxy_buffering off;
    }

    location / {
      proxy_pass https://api.github.com;
      limit_rate 100k;
    }
  }
}

stream {
{{- if eq .log.level "debug" "info" }}
  log_format tcp_log '[$time_local] $remote_addr > https://$ssl_preread_server_name > '
                     '$backend_name ($upstream_addr) '
                     '$upstream_bytes_sent/$upstream_bytes_received ($upstream_connect_time)';
  access_log /dev/stdout tcp_log;
{{- else }}
  access_log off;
{{- end }}

  ssl_preread on;

  # Map incoming SNI to the corresponding backend  
  map $ssl_preread_server_name $backend_name {
  {{- range .local.xray.reality.domains}}
    {{ . }} xray-reality;
  {{- end }}
  {{- range .local.xray.xhttp.domains}}
    {{ . }} terminate-ssl;
  {{- end }}
    {{ .params.telegram.domain }} telegram;
    default drop-conn;
  }

  upstream terminate-ssl { server 172.22.0.02:8443; }
  upstream drop-conn     { server 172.22.0.02:8443 down; }
  upstream xray-reality  { server 172.22.0.11:1443; }
  upstream telegram      { server 172.22.0.12:443;  }

  server {
    listen 443;
    listen [::]:443;

    proxy_pass $backend_name;
  }
}
